version: '3.8'

services:
  dev:
    container_name: tinkering_with_pokeapi-dev
    image: nestjs-api-dev:1.0.0
    build: .
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - serban
    volumes:
      - .:/app
      - /app/node_modules/
    restart: unless-stopped
  prod:
    container_name: tinkering_with_pokeapi-prod
    image: nestjs-api-prod:1.0.0
    build: .
    command: npm run start
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - serban
    volumes:
      - .:/app
      - /app/node_modules/
    restart: unless-stopped

networks:
  serban: